swagger: "2.0"
info:
  title: Room Service
  version: v2

basePath: /services/v1/room

produces:
  - application/json

tags:
  - name: "room"
    description: "Get information about specific rooms"

definitions:
  Patient:
    type: object
    required:
      - binnenkomst
      - minuten_aanwezig
      - status
      - queue
    properties:
      binnenkomst:
        type: string
        format: date-time
        description: RFC3339 tijdstip waarop de patient is binnengekomen
      minuten_aanwezig:
        type: string
        format: int32
        minimum: 0
        description: Aantal minuten dat deze patiënt aanwezig is
      status:
        type: string
        description: Status van de patiënt
        enum:
          - wachtend
          - inbehandeling
      queue:
        type: int
        description: Aantal patiënten die eerder zijn binnengekomen
        format: int32
        minimum: 0

  RoomList:
    type: array
    items:
      $ref: '#/definitions/Room'

  Room:
    type: object
    example:
      {
        "kamernummer": "D10",
        "kamers_bezet": 4,
        "patient": {
          "binnenkomst": "2016-08-12T09:32:35.837Z",
          "minuten_aanwezig": 14,
          "status": "wachtend",
          "queue": 3,
        },
        "arts": "seh",
      }
    required:
      - kamernummer
      - kamers_bezet
    properties:
      kamernummer:
        type: string
        description: Kamernummer
      kamers_bezet:
        type: integer
        format: int32
        description: Het totaal aantal patiënten dat in behandeling is
      patient:
        $ref: "#/definitions/Patient"
      arts:
        type: string
        description: Type arts
        enum:
          - "chi"
          - "seh"
          - "int"
          - "ov"

paths:
  /:
    get:
      summary: Haal overzicht op voor alle beschikbare kamers
      operationId: get_rooms
      tags:
        - room
      parameters:
        - name: t
          in: query
          description: RFC3339 tijdstip waar de kamergegevens voor berekend moeten worden. Default is nu.
          required: false
          type: string
          format: date-time
      responses:
        200:
          description: Kamergegevens voor de kamers waar een patient in ligt
          schema:
            $ref: '#/definitions/RoomList'
        400:
          description: Invalid timestamp

  /{room}:
    get:
      summary: Haal gegevens op voor de opgevraagde kamer
      operationId: get_room
      tags:
        - room
      parameters:
        - name: room
          in: path
          description: Kamernummer
          required: true
          type: string
        - name: t
          in: query
          description: RFC3339 tijdstip waar de kamergegevens voor berekend moeten worden. Default is nu.
          required: false
          type: string
          format: date-time
      responses:
        200:
          description: Kamergegevens voor de opgegeven kamer
          schema:
            $ref: '#/definitions/Room'
        400:
          description: Invalid timestamp
        404:
          description: Onbekende kamer
