swagger: "2.0"
info:
  title: Interrupt Service
  version: v2
  description: |
    De Interrupt Service biedt de mogelijkheid om een soort van 'breaking news' interrupts aan en uit te zetten.
    Op dit moment is er één type interrupt gedefinieerd: de 'spoed-patient' interrupt, die wordt aangezet wanneer er
    een spoedeisende patiënt wordt binnengebracht.

    Bij het opvragen van de interrupt zijn er twee opties: óf de interrupt staat uit, en het resultaat is leeg, óf
    de interrupt staat aan en het resultaat bevat de resterende tijd en waarschuwingstekst.

basePath: /services/v1/interrupts

produces:
  - application/json

definitions:
  InterruptStatusList:
    type: array
    items:
      $ref: '#/definitions/InterruptStatus'

  InterruptStatus:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        enum:
          - spoed-patient
        description: Type interrupt
      seconds_remaining:
        type: integer
        format: int32
        minimum: 0
        description: >
          Aantal seconden dat deze interrupt nog aan blijft staan. Interrupts *kunnen* eerder inactief
          worden, dus dit is meer een indicatie. Afwezig indien er geen interrupt actief is.
      message:
        type: string
        description: Tekst die bij deze interrupt hoort. Afwezig indien er geen interrupt actief is.
    example:
      {
        "type": "spoed-patient",
        "seconds_remaining": 285,
        "message": "Er is een patiënt binnengebracht die al onze aandacht behoeft. Uw behandeling duurt hierdoor mogelijk langer. Bedankt voor uw begrip."
      }

paths:
  /{type}:
    get:
      summary: Haal de status van interrupt `type` op.
      operationId: get_interrupt
      responses:
        200:
          description: De status van de ingestelde interrupt
          schema:
            $ref: '#/definitions/InterruptStatus'

    put:
      summary: Activeer de interrupt `type`.
      operationId: activate_interrupt
      parameters:
        - name: type
          in: path
          description: Het type interrupt
          required: true
          type: string
          enum:
            - spoed-patient
      responses:
        200:
          description: De interrupt is geactiveerd.
          schema:
            $ref: '#/definitions/InterruptStatus'
        404:
          description: Onbekend type interrupt.

    delete:
      summary: Deactiveer de interrupt `type`.
      operationId: deactivate_interrupt
      parameters:
        - name: type
          in: path
          description: Het type interrupt
          required: true
          type: string
          enum:
            - spoed-patient
      responses:
        200:
          description: De interrupt is gedeactiveerd.
        404:
          description: Onbekend type interrupt.

  /:
    get:
      summary: Haal de ingestelde interrupts op.
      operationId: get_interrupts()
      responses:
        200:
          description: De ingestelde interrupts
          schema:
            $ref: '#/definitions/InterruptStatusList'

