openapi: "3.0.0"
info:
  title: Aansluitinformatie Gegevensuitwisseling HAP
  version: 2.0

  description: |

    # Communicatie-stromen

    1. Afspraken -- Topicus is de bron van deze data, en pusht deze naar door2doc
    2. Afspraakvoorstellen -- Door2doc is de bron van deze data, Topicus vraagt de voorstellen op bij door2doc
    3. Blokkades/extra slots -- Topicus is de bron van deze data, en pusht deze naar door2doc
    door2doc

    In alle gevallen is Topicus de initiator van de communicatie -- hetzij door middel van push (bij afspraken), hetzij door middel
    van pull (bij de overige stromen).

    Afspraken worden gepusht bij iedere wijziging in een of meer van de velden die in dit document worden beschreven. Afspraakvoorstellen
    worden gepullt zodra er een afspraakvoorstel nodig is. Blokkades en extra slots worden gepullt wanneer Topicus maar
    wil.

    # Beveiliging

    De beveiliging van de communicatie-stroom naar door2doc bestaat uit de volgende niveaus:

    1. HTTPS:  alle verkeer _moet_ over HTTPS plaatsvinden.
    2. Authenticatie: alle requests naar deze service zijn geauthenticeerd met HTTP Basic Authenticatie

    # Technische constraints

    De service gaat uit van _at least once delivery_; dit betekent dat exact dezelfde afspraak meerdere malen geupload
    mag worden. Met andere woorden: bij het minste vermoeden dat een afspraak niet goed is geupload, kan deze opnieuw
    worden geupload. Dit betekent dat de upload van afspraken ook gebruikt kan worden om historische data te uploaden en/of
    periodieke totaaloverzichten te pushen.

servers:
  - url: https://integration.door2doc.net
    description: Integratie-server van door2doc

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  examples:
    ScheduleList: {
      "resourceType": "List",
      "contained": [
      {
        "resourceType": "Schedule",
        "id": "1",
        "identifier": [
        {
          "system": "urn:topicuszorg:topplan:plekroosterblok:id",
          "value": "1"
        }
        ],
        "actor": [
        {
          "reference": "#3",
        }
        ],
        "planningHorizon": {
          "start": "2018-10-05T10:30:00+02:00",
          "end": "2018-10-05T11:30:00+02:00"
        }
      },
      {
        "resourceType": "Slot",
        "id": "2",
        "serviceType": [
        {
          "coding": [
          {
            "system": "urn:topicuszorg:topplan:afspraakprotocol:code",
            "code": "HuisartsConsult",
          }
          ]
        }
        ],
        "schedule": {
          "reference": "#1"
        },
        "status": "free",
        "start": "2018-10-05T10:30:00.000+02:00",
        "end": "2018-10-05T10:55:00.000+02:00"
      },
      {
        "resourceType": "Location",
        "id": "3",
        "partOf": {
          display: "LUMC"
        }
      }
      ],
      "status": "current",
      "mode": "working",
      "entry": [
      {
        "item": {
          "reference": "#2"
        }
      },
      ]
    }

    OperationalOutcomeSuccess: {
      "resourceType": "OperationOutcome",
      "text": {
        "status": "additional",
        "div": "success"
      },
      "issue": [
      {
        "severity": "information",
        "code": "informational",
        "details": {
          "text": "success"
        }
      }
      ]
    }

    OperationalOutcomeAuth: {
      "resourceType": "OperationOutcome",
      "text": {
        "status": "additional",
        "div": "Unauthorized to access /fhir/v3/List"
      },
      "issue": [
      {
        "severity": "error",
        "code": "security",
        "details": {
          "text": "not authorized"
        },
        "diagnostics": "..."
      }
      ]
    }

    OperationalOutcomeInvalid: {
      "resourceType": "OperationOutcome",
      "text": {
        "status": "additional",
        "div": "invalid resource"
      },
      "issue": [
      {
        "severity": "error",
        "code": "processing",
        "details": {
          "text": "while determining resource type: invalid character 'u' looking for beginning of value"
        },
        "diagnostics": "..."
      },
      {
        "severity": "error",
        "code": "processing",
        "details": {
          "text": "invalid character 'u' looking for beginning of value"
        },
        "diagnostics": "..."
      }
      ]
    }

    OperationalOutcomeInternal: {
      "resourceType": "OperationOutcome",
      "text": {
        "status": "additional",
        "div": "failed to create resource"
      },
      "issue": [
      {
        "severity": "error",
        "code": "processing",
        "details": {
          "text": "..."
        },
        "diagnostics": "..."
      }
      ]
    }

    AppointmentNew: {
      "resourceType": "Appointment",
      "contained": [
      {
        "resourceType": "Patient",
        "id": "1",
        "address": [
        {
          "postalCode": "1001",
          "birthDate": "1970-07-11T08:30:00.000+02:00",
        }
        ]
      },
      {
        "resourceType": "Location",
        "id": "4",
        "name": "Kamer 1",
        "partOf": {
          display: "LUMC"
        }
      }
      ],
      "identifier": [
      {
        "use": "secondary",
        "system": "urn:topicuszorg:topplan:afspraaknummer",
        "value": "123456789"
      }
      ],
      "status": "booked",
      "serviceType": [
      {
        "coding": [
        {
          "system": "urn:topicuszorg:topplan:afspraakprotocol:code",
          "code": "HuisartsConsult"
        }
        ],
      }
      ],
      "start": "2018-10-11T12:00:00.000+02:00",
      "end": "2018-10-11T12:15:00.000+02:00",
      "minutesDuration": 15,
      "participant": [
      {
        "actor": {
          "reference": "#4",
          "display": "Kamer 1"
        },
        "status": "accepted"
      },
      {
        "actor": {
          "reference": "#2"
        },
        "status": "accepted"
      }
      ]
    }


paths:
  /topicus/export/:
    post:
      summary: Regelmatige upload van recent afgeronde en openstaande afspraken.
      operationId: importAfspraken
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  call_id:
                    type: string
                  locatie:
                    type: string
                    example: "leiderdorp"
                  triage_urgentie:
                    type: string
                    enum: ["0", "1", "2", "3", "4", "5"]
                  afsluit_urgentie:
                    type: string
                    enum: ["0", "1", "2", "3", "4", "5"]
                  urgentie_gewijzigd:
                    type: boolean
                  zelfverwijzer:
                    type: boolean
                  aannametijd:
                    type: string
                    format: date-time
                  aankomsttijd:
                    type: string
                    format: date-time
                  originele_afspraak_begintijd:
                    type: string
                    format: date-time
                  urgent_gepland:
                    type: boolean
                  laatste_keer_openen_HA:
                    type: string
                    format: date-time
                  contact_begintijd:
                    type: string
                    format: date-time
                  contact_eindtijd:
                    type: string
                    format: date-time
                  fiatteertijd:
                    type: string
                    format: date-time
                  type_arts:
                    type: string
                    enum: ["Huisarts", "Visitearts", "Nurse-Practitioner"]
                  geboortedatum:
                    type: string
                    format: date-time
                  postcode:
                    type: string
                    example: "7401"
                  ingangsklacht:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        omschrijving:
                          type: string
                    example: [{"id": "45", "omschrijving": "Wond"}]
                  code_icpc:
                    type: string
                    example: "T91.01"
                  actie:
                    type: string
                    example: "Consult"
                  agenda:
                    type: string
                    example: "Kamer 1"
      responses:
        200:
          description: De export is succesvol verwerkt
          content:
            application/json:
              example: {
                "processed": 1
              }
        400:
          description: De export kon niet worden ingelezen
        403:
          description: Authenticatie probleem
        500:
          description: De export kon niet worden verwerkt

  /topicus/propose/:
    post:
      summary: |
        Vraag een afspraak-voorstel op. De afspraak wordt ingeschoten als een FHIR appointment. Het resultaat is een
        FHIR Bundle met nul of meer Slots. De afspraak moet de volgende informatie bevatten:

        * appointmentType: onderscheid tussen zelfverwijzer en niet
        * reason: ingangsklachten van de patiënt
        * priority: initiële triagecode van de patiënt
        * birthdate: geboortedatum van de patiënt, bij voorkeur afgerond naar 1e van de maand
        * postcode: postcode van de patiënt, niet nodig voor zelfverwijzers
        * locatie van waar de call is aangenomen
      operationId: propose
      security:
        - BasicAuth: []
      requestBody:
        description: Een FHIR Appointment
        required: true
        content:
          application/fhir+json:
            example: {
              "resourceType": "Appointment",
              "status": "PROPOSED",
              "appointmentType": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/v2/0276",
                    "code": "WALKIN",
                    "display": "A previously unscheduled walk-in visit"
                  }
                ]
              },
              "reason": [
                {
                  "coding": [
                  {
                    "system": "todo",
                    "code": "45",
                    "display": "Wond"
                  }
                  ]
                }
              ],
              "priority": 3,
              "participant": [
              {
                "actor": {
                  "reference": "#patient1"
                }
              },
              {
                "actor": {
                  "reference": "#location1"
                }
              }
              ],
              "contained": [
              {
                "resourceType": "Patient",
                "id": "patient1",
                "birthDate": "1970-07-11T08:30:00.000+02:00",
                "address": [
                {
                  "postalCode": "7411"
                }
                ]
              },
              {
                "resourceType": "Location",
                "id": "#location1",
                "identifier": [
                {
                  "use": "official",
                  "system": "urn:topicuszorg:topplan:plek:id",
                  "value": "34"
                }
                ],
                "name": "Leiderdorp",
                "managingOrganization": {
                  "reference": "#7"
                }
              },
              {
                "resourceType": "Organization",
                "id": "7",
                "name": "HAP D2D SHR"
              }
              ]
            }
      responses:
        200:
          description: Er is een afspraak voorstel beschikbaar. Het resultaat is een Bundle met nul of meer Slots.
          content:
            application/fhir+json:
              example: {
                "resourceType": "Bundle",
                "type": "searchset",
                "total": 2,
                "entry": [
                {
                  "resource": {
                    "resourceType": "Slot",
                    "schedule": {
                      "reference": "Schedule/35",
                    },
                    "start": "2019-03-18T13:15:00.000+01:00",
                    "end": "2019-03-18T13:30:00.000+01:00"
                  }
                },
                {
                  "resource": {
                    "resourceType": "Slot",
                    "schedule": {
                      "reference": "Schedule/37",
                    },
                    "start": "2019-03-18T13:15:00.000+01:00",
                    "end": "2019-03-18T13:30:00.000+01:00"
                  }
                }
                ]
              }

  /fhir/v3/List:
    post:
      summary: |
        Upload een schedule met 0 of meer slots. Het bestaande schedule wordt in zijn geheel vervangen door het nieuwe
        schedule.
      operationId: postList
      security:
        - BasicAuth: []
      requestBody:
        description: Een FHIR List met daarin één Schedule en 0 of meer Slots.
        required: true
        content:
          application/fhir+json:
            schema:
              example:
                $ref: '#/components/examples/ScheduleList'

      responses:
        201:
          description: De records zijn succesvol verwerkt. Het resultaat is beschreven in een OperationalOutcome.
          content:
            application/fhir+json:
              schema:
                example:
                  $ref: '#/components/examples/OperationalOutcomeSuccess'
        403:
          description: Er was een probleem met het authenticeren. Het probleem is beschreven in een OperationalOutcome.
          content:
            application/fhir+json:
              schema:
                example:
                  $ref: '#/components/examples/OperationalOutcomeAuth'
        422:
          description: Er was een probleem met het uitlezen van één of meerdere resources. Het probleem is beschreven in een OperationalOutcome.
          content:
            application/fhir+json:
              schema:
                example:
                  $ref: '#/components/examples/OperationalOutcomeInvalid'
        500:
          description: Er was een probleem met het verwerken van de upload. Het probleem is beschreven in een OperationalOutcome.
          content:
            application/fhir+json:
              schema:
                example:
                  $ref: '#/components/examples/OperationalOutcomeInternal'

  /fhir/v3/Appointment:
    post:
      summary: |
        Registreer een afspraak. Een bestaande afspraak met hetzelfde ID wordt vervangen.
      operationId: postAppointment
      security:
        - BasicAuth: []
      requestBody:
        description: Een FHIR appointment.
        required: true
        content:
          application/fhir+json:
            schema:
              example:
                $ref: '#/components/examples/AppointmentNew'

        responses:
          201:
            description: De afspraak is succesvol verwerkt. Het resultaat is beschreven in een OperationalOutcome.
            content:
              application/fhir+json:
                schema:
                  example:
                    $ref: '#/components/examples/OperationalOutcomeSuccess'
          403:
            description: Er was een probleem met het authenticeren. Het probleem is beschreven in een OperationalOutcome.
            content:
              application/fhir+json:
                schema:
                  example:
                    $ref: '#/components/examples/OperationalOutcomeAuth'
          422:
            description: Er was een probleem met het uitlezen van de afspraak. Het probleem is beschreven in een OperationalOutcome.
            content:
              application/fhir+json:
                schema:
                  example:
                    $ref: '#/components/examples/OperationalOutcomeInvalid'
          500:
            description: Er was een probleem met het verwerken van de afspraak. Het probleem is beschreven in een OperationalOutcome.
            content:
              application/fhir+json:
                schema:
                  example:
                    $ref: '#/components/examples/OperationalOutcomeInternal'

